req 19 a 24 (menos 22)
tryber/sd-09-project-recipes-app pull request #258
Opened 2021-04-28 20:32 UTC by gabrielmaxgb

2021-04-28 20:39 UTC, analuizams approved these changes

2021-04-28 20:41 UTC, jorgeramires approved these changes

2021-04-28 21:25 UTC, analuizams requested changes
Só estão passando os requisitos 2 e 3. Alguma coisa quebrou 😢

2021-04-28 21:51 UTC, gabrielmaxgb commented
vou olhar

2021-04-28 22:45 UTC, IvanRafael-Dev approved these changes

2021-04-28 22:50 UTC, gabrielmaxgb reviewed
pronto

2021-04-29 00:07 UTC, analuizams approved these changes

2021-04-29 00:07 UTC, merged