Main group 34 req17 18
tryber/sd-09-project-recipes-app pull request #462
Opened 2021-04-30 22:27 UTC by felipedclc

2021-04-30 22:41 UTC, julianadocarmoTI approved these changes

2021-04-30 23:18 UTC, felipeshcolnik approved these changes
Fala xará . Só achei estranho que o gitHub nao me mostrou nada do "código antigo" entao todos os componentes tinham o código todo novo... logo era impossível checar as mudanças feitas em relacao a um commit anterior

2021-04-30 23:20 UTC, felipeshcolnik requested changes
Precisa mudar o diretorio que vai fazer o merge. desta forma, esta indo pra Master @felipedclc 

Valeu maninho, tamo junto! ;)

2021-05-03 17:46 UTC, felipeshcolnik approved these changes

2021-05-03 17:47 UTC, merged